### ISSUE TITLE
What's the use case?

### ISSUE THREAD

**Issue by pocketbird** [panique/php-sass#2]
My apologies if this is the wrong place to put this question.

What's the use case for this?  I can't imagine a scenario where php-sass would be faster than ruby-sass or libsass.  I also can't imagine why your dev environment _wouldn't_ include a task-runner like Grunt or Gulp (both of which work great with the aforementioned sass compilers and compass _and_ work with the current versions) unless you're doing something super simple but then, why wouldn't you just run the ruby compiler on its own (no need to worry about keeping it all php since it's just for dev compilation).  

My tone here isn't accusatory, just general curiosity and a desire to learn.  So, what's the advantage of php-sass over the existing sass compilers?

**Comment by briansea** [comment]
Some People don't want to run Ruby for only this one purpose, if everything else in your stack is php. :)

**Comment by panique** [comment]
Hey, I've answered this already too often in several blog posts and also the readmes say this (at least I think so... hmmm...), so this time just a very short answer:

php-sass is just a renamed version of [laravel-sass](https://github.com/panique/laravel-sass), renamed because it was initially made for config-free and install-free easy use with laravel, but gained some "popularity" also outside of laravel, so people are not confused and think "oh it just works with laravel".

The idea of the project was to compile SASS to CSS in the most simple way possible without having to setup the classic ruby setup first (and the configuration, the restarts etc). At that time grunt/gulp were not standard in the development world. It was just a personal project, I never planned that other people really use this :) At that time the idea of putting one line of pure PHP code into the project without having to setup nodejs+gulp/grunt+bower etc first just felt right...

Today it's for sure not super-useful anymore as most applications use gulp/grunt as task-runners for this, and I'm also not using laravel-sass in my professional jobs anymore.

The project is already 3-4 years old, but I think it's okay to keep it online. The laravel-version of php-sass has 11.000 downloads [according to Packagist](https://packagist.org/packages/panique/laravel-sass), so some people are really using it, and removing it from Github would result in broken applications, so there's also no proper way to say "let's put this project slowly to an End of Life".

Have a wonderful week,
Chris

**Comment by pocketbird** [comment]
I didn't realize the project was 3-4 years old.  I totally get not wanting to setup ruby if it's a hassle - although, (rubyinstaller.org)[http://rubyinstaller.org/] is pretty straightforward.  And I also understand the desire to keep a project all in php if everything else in your stack is php (although, when you're talking about development - and especially something that just runs globally on your machine to compile sass, you're not really adding Ruby to your stack).  

Anyway, thanks for the quick reply!  I saw the project popup in the (webdesignerdepot)[http://www.webdesignerdepot.com/] twitter feed and got curious.
